### ISSUE TITLE
Running project after compilation

### ISSUE THREAD

**Issue by bgalb** [itoshkov/nand2tetris-emu#10]
Hi!(maven newbie here)
After running mvn install from the root dir, I moved all of the relevant resources(jars, classes) to their destination in InstallDir, but for some reason when I change the code and re-compile, the changes don't seem to take effect(while in my IDE they do). Any idea what's going on?

**Comment by itoshkov** [comment]
The easiest way to build the project is by using the included [`release.sh`](https://github.com/itoshkov/nand2tetris-emu/blob/master/release.sh). It will build the project, put the `.jar` files in the correct directory and package everything in a zip file. Have you tried using it?

**Comment by bgalb** [comment]
I've written my own batch script as I'm running windows, but after taking a look at release.sh I've found the problem, so thank you!
By the way, I'm working on an official re-release of the suite, so if you remember any bugs/things that needed change I'd love to hear.

**Comment by itoshkov** [comment]
Oh! Like Official official build? That's good!

I'll open new bugs in this project, describing the major problems that I've found.
