### ISSUE TITLE
VMEmulator built-in classes not useable from command line

### ISSUE THREAD

**Issue by markarmb** [itoshkov/nand2tetris-emu#2]
When running a .tst script from the command line, built-in classes cannot by used.  The "No implementation was found..." message does not appear.

I propose that an environment variable be used to control this behavior when running without GUI.  This would allow, for example:

    export VMEBUILTIN=yes
    VMEmulator whatever.tst

(Environment variable is preferred over a command line option so that the user doesn't need to edit the VMEmulator sh/bat.)

This is not a trivial fix, however.  The built-in class runner appears to be tied to the GUI thread.
From the CPU class's constructor:

       if (program.getGUI() != null) {
            builtInFunctionsRunner =
                new BuiltInFunctionsRunner(this, builtInDir);
        }

**Comment by itoshkov** [comment]
Fixed with commit 6f28006.

I've changed the variable name to N2T_VM_USE_BUILTINS. See the commit comment for possible values and how they affect the behavriour.
